# config/services.yaml
parameters:
  modules_upload_dir: '%kernel.project_dir%/public/uploads/modules'
  events_upload_dir: '%kernel.project_dir%/public/uploads/events'
  locations_upload_dir: '%kernel.project_dir%/public/uploads/locations'
  hf_token: '%env(HF_TOKEN)%'
  hf_model: '%env(HF_MODEL)%'
  reclamations_directory: '%kernel.project_dir%/public/uploads/reclamations'
  ollama_url: '%env(OLLAMA_URL)%'
  ollama_model: '%env(OLLAMA_MODEL)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Service\OllamaTutorService:
    arguments:
      $ollamaUrl: '%ollama_url%'
      $ollamaModel: '%ollama_model%'

  App\Service\AIService:
    arguments:
      $aiUrl: '%env(PYTHON_AI_URL)%'

  App\Service\HuggingFaceTutorService:
    arguments:
      $hfToken: '%hf_token%'
      $hfModel: '%hf_model%'

  App\Service\GeminiTranslatorService:
    arguments:
      $geminiApiKey: '%env(GEMINI_API_KEY)%'