# config/services.yaml
parameters:
  modules_upload_dir: '%kernel.project_dir%/public/uploads/modules'
  events_upload_dir: '%kernel.project_dir%/public/uploads/events'
  locations_upload_dir: '%kernel.project_dir%/public/uploads/locations'
  hf_token: '%env(HF_TOKEN)%'
  hf_model: '%env(HF_MODEL)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Service\HuggingFaceTutorService:
    arguments:
      $hfToken: '%hf_token%'
      $hfModel: '%hf_model%'
