name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: PHPStan & PHPUnit
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: skillpathdb_test
        options: >-
          --health-cmd "mysqladmin ping -uroot -proot"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3306:3306

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: pdo, pdo_mysql, intl, zip, mbstring, gd, iconv
          coverage: none

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        env:
          APP_ENV: dev
          APP_SECRET: testsecret
          DATABASE_URL: "mysql://root:root@127.0.0.1:3306/skillpathdb_test?serverVersion=8.0&charset=utf8mb4"
        run: composer install --no-interaction --no-progress --optimize-autoloader

      - name: PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=512M --no-progress

      - name: Initialize Test Database
        env:
          DATABASE_URL: "mysql://root:root@127.0.0.1:3306/skillpathdb_test?serverVersion=8.0&charset=utf8mb4"
        run: |
          php bin/console doctrine:database:create --env=test --if-not-exists
          php bin/console doctrine:schema:update --force --env=test

      - name: PHPUnit
        env:
          APP_ENV: test
          APP_SECRET: testsecret
          DATABASE_URL: "mysql://root:root@127.0.0.1:3306/skillpathdb_test?serverVersion=8.0&charset=utf8mb4"
        run: php bin/phpunit --testdox

  docker-test:
    name: Test Docker Compose Build
    needs: tests # Ne s'exécute QUE si le job 'tests' au-dessus est validé
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Start Containers
        run: docker compose up -d --build

      - name: Verify Running Containers
        run: docker compose ps
